### ISSUE TITLE
Errors with Dokuwiki 2023-04-04a “Jack Jackrum”

### ISSUE THREAD

**Issue by Miro-Collas** [Chris--S/dokuwiki-plugin-iframe#14]
```
2023-08-16 22:41:10E_WARNING: Undefined array key 1/home/fswiki/public_html/lib/plugins/iframe/syntax.php(26)
    #0 /home/fswiki/public_html/lib/plugins/iframe/syntax.php(26): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/home/fswiki/pu...', 26)
    #1 /home/fswiki/public_html/inc/parser/handler.php(284): syntax_plugin_iframe->handle('https://teamup....', 5, 1066, Object(Doku_Handler))
    #2 /home/fswiki/public_html/inc/Parsing/Lexer/Lexer.php(270): Doku_Handler->plugin('{{url>https://t...', 5, 1066, 'iframe')
    #3 /home/fswiki/public_html/inc/Parsing/Lexer/Lexer.php(197): dokuwiki\Parsing\Lexer\Lexer->invokeHandler('{{url>https://t...', 5, 1066)
    #4 /home/fswiki/public_html/inc/Parsing/Lexer/Lexer.php(147): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens('', '{{url>https://t...', '_plugin_iframe', 1066, 1066)
    #5 /home/fswiki/public_html/inc/Parsing/Parser.php(109): dokuwiki\Parsing\Lexer\Lexer->parse('\n')
    #6 /home/fswiki/public_html/inc/parserutils.php(234): dokuwiki\Parsing\Parser->parse('\n{{tag>help cla...')
    #7 /home/fswiki/public_html/inc/parserutils.php(198): p_get_instructions('{{tag>help clas...')
    #8 /home/fswiki/public_html/inc/parserutils.php(525): p_cached_instructions('/home/fswiki/pu...', false, 'firestorm_class...')
    #9 /home/fswiki/public_html/inc/parserutils.php(299): p_render_metadata('firestorm_class...', Array)
    #10 /home/fswiki/public_html/inc/common.php(266): p_get_metadata('firestorm_class...')
    #11 /home/fswiki/public_html/doku.php(97): pageinfo()
    #12 {main}

2023-08-16 22:41:10E_WARNING: Undefined array key 4/home/fswiki/public_html/lib/plugins/iframe/syntax.php(48)
    #0 /home/fswiki/public_html/lib/plugins/iframe/syntax.php(48): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/home/fswiki/pu...', 48)
    #1 /home/fswiki/public_html/inc/parser/handler.php(284): syntax_plugin_iframe->handle('https://teamup....', 5, 1066, Object(Doku_Handler))
    #2 /home/fswiki/public_html/inc/Parsing/Lexer/Lexer.php(270): Doku_Handler->plugin('{{url>https://t...', 5, 1066, 'iframe')
    #3 /home/fswiki/public_html/inc/Parsing/Lexer/Lexer.php(197): dokuwiki\Parsing\Lexer\Lexer->invokeHandler('{{url>https://t...', 5, 1066)
    #4 /home/fswiki/public_html/inc/Parsing/Lexer/Lexer.php(147): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens('', '{{url>https://t...', '_plugin_iframe', 1066, 1066)
    #5 /home/fswiki/public_html/inc/Parsing/Parser.php(109): dokuwiki\Parsing\Lexer\Lexer->parse('\n')
    #6 /home/fswiki/public_html/inc/parserutils.php(234): dokuwiki\Parsing\Parser->parse('\n{{tag>help cla...')
    #7 /home/fswiki/public_html/inc/parserutils.php(198): p_get_instructions('{{tag>help clas...')
    #8 /home/fswiki/public_html/inc/parserutils.php(525): p_cached_instructions('/home/fswiki/pu...', false, 'firestorm_class...')
    #9 /home/fswiki/public_html/inc/parserutils.php(299): p_render_metadata('firestorm_class...', Array)
    #10 /home/fswiki/public_html/inc/common.php(266): p_get_metadata('firestorm_class...')
    #11 /home/fswiki/public_html/doku.php(97): pageinfo()
    #12 {main}

2023-08-16 22:41:10E_WARNING: Undefined variable $alt/home/fswiki/public_html/lib/plugins/iframe/syntax.php(90)
    #0 /home/fswiki/public_html/lib/plugins/iframe/syntax.php(90): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined varia...', '/home/fswiki/pu...', 90)
    #1 /home/fswiki/public_html/inc/parser/renderer.php(119): syntax_plugin_iframe->render('xhtml', Object(Doku_Renderer_xhtml), Array)
    #2 /home/fswiki/public_html/inc/parserutils.php(700): Doku_Renderer->plugin('iframe', Array, 5, '{{url>https://t...')
    #3 /home/fswiki/public_html/inc/parserutils.php(158): p_render('xhtml', Array, NULL)
    #4 /home/fswiki/public_html/inc/parserutils.php(96): p_cached_output('/home/fswiki/pu...', 'xhtml', 'firestorm_class...')
    #5 /home/fswiki/public_html/inc/Ui/PageView.php(68): p_wiki_xhtml('firestorm_class...', 0, true, '')
    #6 /home/fswiki/public_html/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
    #7 /home/fswiki/public_html/inc/template.php(100): dokuwiki\Action\Show->tplContent()
    #8 [internal function]: tpl_content_core('show')
    #9 /home/fswiki/public_html/inc/Extension/Event.php(133): call_user_func_array('tpl_content_cor...', Array)
    #10 /home/fswiki/public_html/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger('tpl_content_cor...', true)
    #11 /home/fswiki/public_html/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger('TPL_ACT_RENDER', 'show', 'tpl_content_cor...')
    #12 /home/fswiki/public_html/lib/tpl/bootstrap3/main.php(117): tpl_content(false)
    #13 /home/fswiki/public_html/inc/actions.php(27): include('/home/fswiki/pu...')
    #14 /home/fswiki/public_html/doku.php(126): act_dispatch()
    #15 {main}
```

**Comment by Miro-Collas** [comment]
Attempted fix in
https://github.com/Chris--S/dokuwiki-plugin-iframe/pull/15

**Comment by Miro-Collas** [comment]
Attempted fix in #15

**Comment by yaynstuff** [comment]
Last commit in 2016 - doesn't fill one with a lot of confidence that this plugin is being maintained..

**Comment by Miro-Collas** [comment]
> Last commit in 2016 - doesn't fill one with a lot of confidence that this plugin is being maintained..

It doesn't, which is why I tried to fix it myself.

**Comment by Chris--S** [comment]
fixed.
